import { Color } from '../types';

const colors: Color[] = [
  {
    color: 'MediumVioletRed',
    category: 'x11',
    hex: '#C71585',
    family: 'pink',
  },
  {
    color: 'DeepPink',
    category: 'x11',
    hex: '#FF1493',
    family: 'pink',
  },
  {
    color: 'PaleVioletRed',
    category: 'x11',
    hex: '#DB7093',
    family: 'pink',
  },
  {
    color: 'HotPink',
    category: 'x11',
    hex: '#FF69B4',
    family: 'pink',
  },
  {
    color: 'LightPink',
    category: 'x11',
    hex: '#FFB6C1',
    family: 'pink',
  },
  {
    color: 'Pink',
    category: 'x11',
    hex: '#FFC0CB',
    family: 'pink',
  },
  {
    color: 'DarkRed',
    category: 'x11',
    hex: '#8B0000',
    family: 'red',
  },
  {
    color: 'Red',
    category: 'html',
    hex: '#FF0000',
    family: 'red',
  },
  {
    color: 'Firebrick',
    category: 'x11',
    hex: '#B22222',
    family: 'red',
  },
  {
    color: 'Crimson',
    category: 'x11',
    hex: '#DC143C',
    family: 'red',
  },
  {
    color: 'IndianRed',
    category: 'x11',
    hex: '#CD5C5C',
    family: 'red',
  },
  {
    color: 'LightCoral',
    category: 'x11',
    hex: '#F08080',
    family: 'red',
  },
  {
    color: 'Salmon',
    category: 'x11',
    hex: '#FA8072',
    family: 'red',
  },
  {
    color: 'DarkSalmon',
    category: 'x11',
    hex: '#E9967A',
    family: 'red',
  },
  {
    color: 'LightSalmon',
    category: 'x11',
    hex: '#FFA07A',
    family: 'red',
  },
  {
    color: 'OrangeRed',
    category: 'x11',
    hex: '#FF4500',
    family: 'orange',
  },
  {
    color: 'Tomato',
    category: 'x11',
    hex: '#FF6347',
    family: 'orange',
  },
  {
    color: 'DarkOrange',
    category: 'x11',
    hex: '#FF8C00',
    family: 'orange',
  },
  {
    color: 'Coral',
    category: 'x11',
    hex: '#FF7F50',
    family: 'orange',
  },
  {
    color: 'Orange',
    category: '2_1',
    hex: '#FFA500',
    family: 'orange',
  },
  {
    color: 'DarkKhaki',
    category: 'x11',
    hex: '#BDB76B',
    family: 'yellow',
  },
  {
    color: 'Gold',
    category: 'x11',
    hex: '#FFD700',
    family: 'yellow',
  },
  {
    color: 'Khaki',
    category: 'x11',
    hex: '#F0E68C',
    family: 'yellow',
  },
  {
    color: 'PeachPuff',
    category: 'x11',
    hex: '#FFDAB9',
    family: 'yellow',
  },
  {
    color: 'Yellow',
    category: 'html',
    hex: '#FFFF00',
    family: 'yellow',
  },
  {
    color: 'PaleGoldenrod',
    category: 'x11',
    hex: '#EEE8AA',
    family: 'yellow',
  },
  {
    color: 'Moccasin',
    category: 'x11',
    hex: '#FFE4B5',
    family: 'yellow',
  },
  {
    color: 'PapayaWhip',
    category: 'x11',
    hex: '#FFEFD5',
    family: 'yellow',
  },
  {
    color: 'LightGoldenrodYellow',
    category: 'x11',
    hex: '#FAFAD2',
    family: 'yellow',
  },
  {
    color: 'LemonChiffon',
    category: 'x11',
    hex: '#FFFACD',
    family: 'yellow',
  },
  {
    color: 'LightYellow',
    category: 'x11',
    hex: '#FFFFE0',
    family: 'yellow',
  },
  {
    color: 'Maroon',
    category: 'html',
    hex: '#800000',
    family: 'brown',
  },
  {
    color: 'Brown',
    category: 'x11',
    hex: '#A52A2A',
    family: 'brown',
  },
  {
    color: 'SaddleBrown',
    category: 'x11',
    hex: '#8B4513',
    family: 'brown',
  },
  {
    color: 'Sienna',
    category: 'x11',
    hex: '#A0522D',
    family: 'brown',
  },
  {
    color: 'Chocolate',
    category: 'x11',
    hex: '#D2691E',
    family: 'brown',
  },
  {
    color: 'DarkGoldenrod',
    category: 'x11',
    hex: '#B8860B',
    family: 'brown',
  },
  {
    color: 'Peru',
    category: 'x11',
    hex: '#CD853F',
    family: 'brown',
  },
  {
    color: 'RosyBrown',
    category: 'x11',
    hex: '#BC8F8F',
    family: 'brown',
  },
  {
    color: 'Goldenrod',
    category: 'x11',
    hex: '#DAA520',
    family: 'brown',
  },
  {
    color: 'SandyBrown',
    category: 'x11',
    hex: '#F4A460',
    family: 'brown',
  },
  {
    color: 'Tan',
    category: 'x11',
    hex: '#D2B48C',
    family: 'brown',
  },
  {
    color: 'Burlywood',
    category: 'x11',
    hex: '#DEB887',
    family: 'brown',
  },
  {
    color: 'Wheat',
    category: 'x11',
    hex: '#F5DEB3',
    family: 'brown',
  },
  {
    color: 'NavajoWhite',
    category: 'x11',
    hex: '#FFDEAD',
    family: 'brown',
  },
  {
    color: 'Bisque',
    category: 'x11',
    hex: '#FFE4C4',
    family: 'brown',
  },
  {
    color: 'BlanchedAlmond',
    category: 'x11',
    hex: '#FFEBCD',
    family: 'brown',
  },
  {
    color: 'Cornsilk',
    category: 'x11',
    hex: '#FFF8DC',
    family: 'brown',
  },
  {
    color: 'DarkGreen',
    category: 'x11',
    hex: '#006400',
    family: 'green',
  },
  {
    color: 'Green',
    category: 'html',
    hex: '#008000',
    family: 'green',
  },
  {
    color: 'DarkOliveGreen',
    category: 'x11',
    hex: '#556B2F',
    family: 'green',
  },
  {
    color: 'ForestGreen',
    category: 'x11',
    hex: '#228B22',
    family: 'green',
  },
  {
    color: 'SeaGreen',
    category: 'x11',
    hex: '#2E8B57',
    family: 'green',
  },
  {
    color: 'Olive',
    category: 'html',
    hex: '#808000',
    family: 'green',
  },
  {
    color: 'OliveDrab',
    category: 'x11',
    hex: '#6B8E23',
    family: 'green',
  },
  {
    color: 'MediumSeaGreen',
    category: 'x11',
    hex: '#3CB371',
    family: 'green',
  },
  {
    color: 'LimeGreen',
    category: 'x11',
    hex: '#32CD32',
    family: 'green',
  },
  {
    color: 'Lime',
    category: 'html',
    hex: '#00FF00',
    family: 'green',
  },
  {
    color: 'SpringGreen',
    category: 'x11',
    hex: '#00FF7F',
    family: 'green',
  },
  {
    color: 'MediumSpringGreen',
    category: 'x11',
    hex: '#00FA9A',
    family: 'green',
  },
  {
    color: 'DarkSeaGreen',
    category: 'x11',
    hex: '#8FBC8F',
    family: 'green',
  },
  {
    color: 'MediumAquamarine',
    category: 'x11',
    hex: '#66CDAA',
    family: 'green',
  },
  {
    color: 'YellowGreen',
    category: 'x11',
    hex: '#9ACD32',
    family: 'green',
  },
  {
    color: 'LawnGreen',
    category: 'x11',
    hex: '#7CFC00',
    family: 'green',
  },
  {
    color: 'Chartreuse',
    category: 'x11',
    hex: '#7FFF00',
    family: 'green',
  },
  {
    color: 'LightGreen',
    category: 'x11',
    hex: '#90EE90',
    family: 'green',
  },
  {
    color: 'GreenYellow',
    category: 'x11',
    hex: '#ADFF2F',
    family: 'green',
  },
  {
    color: 'PaleGreen',
    category: 'x11',
    hex: '#98FB98',
    family: 'green',
  },
  {
    color: 'Teal',
    category: 'html',
    hex: '#008080',
    family: 'cyan',
  },
  {
    color: 'DarkCyan',
    category: 'x11',
    hex: '#008B8B',
    family: 'cyan',
  },
  {
    color: 'LightSeaGreen',
    category: 'x11',
    hex: '#20B2AA',
    family: 'cyan',
  },
  {
    color: 'CadetBlue',
    category: 'x11',
    hex: '#5F9EA0',
    family: 'cyan',
  },
  {
    color: 'DarkTurquoise',
    category: 'x11',
    hex: '#00CED1',
    family: 'cyan',
  },
  {
    color: 'MediumTurquoise',
    category: 'x11',
    hex: '#48D1CC',
    family: 'cyan',
  },
  {
    color: 'Turquoise',
    category: 'x11',
    hex: '#40E0D0',
    family: 'cyan',
  },
  {
    color: 'Aqua',
    category: 'html',
    hex: '#00FFFF',
    family: 'cyan',
  },
  {
    color: 'Aquamarine',
    category: 'x11',
    hex: '#7FFFD4',
    family: 'cyan',
  },
  {
    color: 'PaleTurquoise',
    category: 'x11',
    hex: '#AFEEEE',
    family: 'cyan',
  },
  {
    color: 'LightCyan',
    category: 'x11',
    hex: '#E0FFFF',
    family: 'cyan',
  },
  {
    color: 'Navy',
    category: 'html',
    hex: '#000080',
    family: 'blue',
  },
  {
    color: 'DarkBlue',
    category: 'x11',
    hex: '#00008B',
    family: 'blue',
  },
  {
    color: 'MediumBlue',
    category: 'x11',
    hex: '#0000CD',
    family: 'blue',
  },
  {
    color: 'Blue',
    category: 'html',
    hex: '#0000FF',
    family: 'blue',
  },
  {
    color: 'MidnightBlue',
    category: 'x11',
    hex: '#191970',
    family: 'blue',
  },
  {
    color: 'RoyalBlue',
    category: 'x11',
    hex: '#4169E1',
    family: 'blue',
  },
  {
    color: 'SteelBlue',
    category: 'x11',
    hex: '#4682B4',
    family: 'blue',
  },
  {
    color: 'DodgerBlue',
    category: 'x11',
    hex: '#1E90FF',
    family: 'blue',
  },
  {
    color: 'DeepSkyBlue',
    category: 'x11',
    hex: '#00BFFF',
    family: 'blue',
  },
  {
    color: 'CornflowerBlue',
    category: 'x11',
    hex: '#6495ED',
    family: 'blue',
  },
  {
    color: 'SkyBlue',
    category: 'x11',
    hex: '#87CEEB',
    family: 'blue',
  },
  {
    color: 'LightSkyBlue',
    category: 'x11',
    hex: '#87CEFA',
    family: 'blue',
  },
  {
    color: 'LightSteelBlue',
    category: 'x11',
    hex: '#B0C4DE',
    family: 'blue',
  },
  {
    color: 'LightBlue',
    category: 'x11',
    hex: '#ADD8E6',
    family: 'blue',
  },
  {
    color: 'PowderBlue',
    category: 'x11',
    hex: '#B0E0E6',
    family: 'blue',
  },
  {
    color: 'Indigo',
    category: 'x11',
    hex: '#4B0082',
    family: 'purple',
  },
  {
    color: 'Purple',
    category: 'html',
    hex: '#800080',
    family: 'purple',
  },
  {
    color: 'DarkMagenta',
    category: 'x11',
    hex: '#8B008B',
    family: 'purple',
  },
  {
    color: 'DarkViolet',
    category: 'x11',
    hex: '#9400D3',
    family: 'purple',
  },
  {
    color: 'DarkSlateBlue',
    category: 'x11',
    hex: '#483D8B',
    family: 'purple',
  },
  {
    color: 'BlueViolet',
    category: 'x11',
    hex: '#8A2BE2',
    family: 'purple',
  },
  {
    color: 'DarkOrchid',
    category: 'x11',
    hex: '#9932CC',
    family: 'purple',
  },
  {
    color: 'Fuchsia',
    category: 'html',
    hex: '#FF00FF',
    family: 'purple',
  },
  {
    color: 'SlateBlue',
    category: 'x11',
    hex: '#6A5ACD',
    family: 'purple',
  },
  {
    color: 'MediumSlateBlue',
    category: 'x11',
    hex: '#7B68EE',
    family: 'purple',
  },
  {
    color: 'MediumOrchid',
    category: 'x11',
    hex: '#BA55D3',
    family: 'purple',
  },
  {
    color: 'MediumPurple',
    category: 'x11',
    hex: '#9370DB',
    family: 'purple',
  },
  {
    color: 'Orchid',
    category: 'x11',
    hex: '#DA70D6',
    family: 'purple',
  },
  {
    color: 'Violet',
    category: 'x11',
    hex: '#EE82EE',
    family: 'purple',
  },
  {
    color: 'Plum',
    category: 'x11',
    hex: '#DDA0DD',
    family: 'purple',
  },
  {
    color: 'Thistle',
    category: 'x11',
    hex: '#D8BFD8',
    family: 'purple',
  },
  {
    color: 'Lavender',
    category: 'x11',
    hex: '#E6E6FA',
    family: 'purple',
  },
  {
    color: 'MistyRose',
    category: 'x11',
    hex: '#FFE4E1',
    family: 'white',
  },
  {
    color: 'AntiqueWhite',
    category: 'x11',
    hex: '#FAEBD7',
    family: 'white',
  },
  {
    color: 'Linen',
    category: 'x11',
    hex: '#FAF0E6',
    family: 'white',
  },
  {
    color: 'Beige',
    category: 'x11',
    hex: '#F5F5DC',
    family: 'white',
  },
  {
    color: 'WhiteSmoke',
    category: 'x11',
    hex: '#F5F5F5',
    family: 'white',
  },
  {
    color: 'LavenderBlush',
    category: 'x11',
    hex: '#FFF0F5',
    family: 'white',
  },
  {
    color: 'OldLace',
    category: 'x11',
    hex: '#FDF5E6',
    family: 'white',
  },
  {
    color: 'AliceBlue',
    category: 'x11',
    hex: '#F0F8FF',
    family: 'white',
  },
  {
    color: 'Seashell',
    category: 'x11',
    hex: '#FFF5EE',
    family: 'white',
  },
  {
    color: 'GhostWhite',
    category: 'x11',
    hex: '#F8F8FF',
    family: 'white',
  },
  {
    color: 'Honeydew',
    category: 'x11',
    hex: '#F0FFF0',
    family: 'white',
  },
  {
    color: 'FloralWhite',
    category: 'x11',
    hex: '#FFFAF0',
    family: 'white',
  },
  {
    color: 'Azure',
    category: 'x11',
    hex: '#F0FFFF',
    family: 'white',
  },
  {
    color: 'MintCream',
    category: 'x11',
    hex: '#F5FFFA',
    family: 'white',
  },
  {
    color: 'Snow',
    category: 'x11',
    hex: '#FFFAFA',
    family: 'white',
  },
  {
    color: 'Ivory',
    category: 'x11',
    hex: '#FFFFF0',
    family: 'white',
  },
  {
    color: 'White',
    category: 'html',
    hex: '#FFFFFF',
    family: 'white',
  },
  {
    color: 'Black',
    category: 'html',
    hex: '#000000',
    family: 'gray',
  },
  {
    color: 'DarkSlateGray',
    category: 'x11',
    hex: '#2F4F4F',
    family: 'gray',
  },
  {
    color: 'DimGray',
    category: 'x11',
    hex: '#696969',
    family: 'gray',
  },
  {
    color: 'SlateGray',
    category: 'x11',
    hex: '#708090',
    family: 'gray',
  },
  {
    color: 'Gray',
    category: 'html',
    hex: '#808080',
    family: 'gray',
  },
  {
    color: 'LightSlateGray',
    category: 'x11',
    hex: '#778899',
    family: 'gray',
  },
  {
    color: 'DarkGray',
    category: 'x11',
    hex: '#A9A9A9',
    family: 'gray',
  },
  {
    color: 'Silver',
    category: 'html',
    hex: '#C0C0C0',
    family: 'gray',
  },
  {
    color: 'LightGray',
    category: 'x11',
    hex: '#D3D3D3',
    family: 'gray',
  },
  {
    color: 'Gainsboro',
    category: 'x11',
    hex: '#DCDCDC',
    family: 'gray',
  },
  {
    color: 'RebeccaPurple',
    category: 'special',
    hex: '#663399',
    family: 'purple',
  },
];

export default colors;
